### ISSUE TITLE
RFC Process

### ISSUE THREAD

**Issue by JP-Ellis** [pact-foundation/roadmap#32]
## Summary

Introduce a process to request for comments (RFC) for changes which will impact Pact as a whole.

## Motivation

The Pact Foundation has always wanted to be transparent in the way new features are added to Pact, and while most of the information can be discovered (whether it be from some issue thread, Slack discussion or otherwise), the information may not always be as discoverable as desired.

By formalising a RFC process and storing the discussion in a centralised location, we hope to make the process much more discoverable.

## Suggestion

In my experience, the [Rust RFC process](https://github.com/rust-lang/rfcs) is excellent, albeit perhaps too rigorous for Pact's needs. I would suggest adopting a similar approach for Pact, with some adjustments made to be more lightweight.

### Scopes

The Pact ecosystem is split across a number of languages, and therefore part of the initial discussion will be deciding what should go within the scope of the RFCs.

**Comment by mefellows** [comment]
Closed by https://github.com/pact-foundation/roadmap/pull/96.
